/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface UniswapV2PairMockInterface extends ethers.utils.Interface {
  functions: {
    "blockTimestamp()": FunctionFragment;
    "getReserves()": FunctionFragment;
    "price0CumulativeLast()": FunctionFragment;
    "price1CumulativeLast()": FunctionFragment;
    "reserves0()": FunctionFragment;
    "reserves1()": FunctionFragment;
    "setCumulativePrices(uint256,uint256)": FunctionFragment;
    "setReserves(uint112,uint112,uint32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "blockTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "price0CumulativeLast",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "price1CumulativeLast",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reserves0", values?: undefined): string;
  encodeFunctionData(functionFragment: "reserves1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setCumulativePrices",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserves",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "blockTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "price0CumulativeLast",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "price1CumulativeLast",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserves0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reserves1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCumulativePrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserves",
    data: BytesLike
  ): Result;

  events: {};
}

export class UniswapV2PairMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UniswapV2PairMockInterface;

  functions: {
    blockTimestamp(overrides?: CallOverrides): Promise<[number]>;

    getReserves(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    price0CumulativeLast(overrides?: CallOverrides): Promise<[BigNumber]>;

    price1CumulativeLast(overrides?: CallOverrides): Promise<[BigNumber]>;

    reserves0(overrides?: CallOverrides): Promise<[BigNumber]>;

    reserves1(overrides?: CallOverrides): Promise<[BigNumber]>;

    setCumulativePrices(
      cumPrice0: BigNumberish,
      cumPrice1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setReserves(
      reserves0_: BigNumberish,
      reserves1_: BigNumberish,
      blockTimestamp_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  blockTimestamp(overrides?: CallOverrides): Promise<number>;

  getReserves(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, number]>;

  price0CumulativeLast(overrides?: CallOverrides): Promise<BigNumber>;

  price1CumulativeLast(overrides?: CallOverrides): Promise<BigNumber>;

  reserves0(overrides?: CallOverrides): Promise<BigNumber>;

  reserves1(overrides?: CallOverrides): Promise<BigNumber>;

  setCumulativePrices(
    cumPrice0: BigNumberish,
    cumPrice1: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setReserves(
    reserves0_: BigNumberish,
    reserves1_: BigNumberish,
    blockTimestamp_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    blockTimestamp(overrides?: CallOverrides): Promise<number>;

    getReserves(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, number]>;

    price0CumulativeLast(overrides?: CallOverrides): Promise<BigNumber>;

    price1CumulativeLast(overrides?: CallOverrides): Promise<BigNumber>;

    reserves0(overrides?: CallOverrides): Promise<BigNumber>;

    reserves1(overrides?: CallOverrides): Promise<BigNumber>;

    setCumulativePrices(
      cumPrice0: BigNumberish,
      cumPrice1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setReserves(
      reserves0_: BigNumberish,
      reserves1_: BigNumberish,
      blockTimestamp_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    blockTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    getReserves(overrides?: CallOverrides): Promise<BigNumber>;

    price0CumulativeLast(overrides?: CallOverrides): Promise<BigNumber>;

    price1CumulativeLast(overrides?: CallOverrides): Promise<BigNumber>;

    reserves0(overrides?: CallOverrides): Promise<BigNumber>;

    reserves1(overrides?: CallOverrides): Promise<BigNumber>;

    setCumulativePrices(
      cumPrice0: BigNumberish,
      cumPrice1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setReserves(
      reserves0_: BigNumberish,
      reserves1_: BigNumberish,
      blockTimestamp_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    blockTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getReserves(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    price0CumulativeLast(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    price1CumulativeLast(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reserves0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reserves1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setCumulativePrices(
      cumPrice0: BigNumberish,
      cumPrice1: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setReserves(
      reserves0_: BigNumberish,
      reserves1_: BigNumberish,
      blockTimestamp_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
