/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILadle, ILadleInterface } from "../ILadle";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes6",
        name: "assetId",
        type: "bytes6",
      },
    ],
    name: "joins",
    outputs: [
      {
        internalType: "contract IJoin",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILadle__factory {
  static readonly abi = _abi;
  static createInterface(): ILadleInterface {
    return new utils.Interface(_abi) as ILadleInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ILadle {
    return new Contract(address, _abi, signerOrProvider) as ILadle;
  }
}
